#! / usr / bin / env php
<? php
define ( ' LARAVEL_START ' , microtime ( true ));
/ *
| ------------------------------------------------- -------------------------
| Registrar o carregador automático
| ------------------------------------------------- -------------------------
|
| O Composer fornece um carregador de classes conveniente e gerado automaticamente
| para a nossa aplicação. Nós apenas precisamos utilizá-lo! Vamos exigir
| no script aqui para que não tenhamos que nos preocupar com o
| carregamento de qualquer uma de nossas classes "manualmente". É ótimo relaxar.
|
* /
exigir  __DIR__ . ' /vendor/autoload.php ' ;
$ app  =  require_once  __DIR__ . ' /bootstrap/app.php ' ;
/ *
| ------------------------------------------------- -------------------------
| Executar o aplicativo Artisan
| ------------------------------------------------- -------------------------
|
| Quando executamos o aplicativo de console, o comando CLI atual será
| executado neste console e a resposta enviada de volta para um terminal
| ou outro dispositivo de saída para os desenvolvedores. Aqui vai nada!
|
* /
$ kernel  =  $ app -> make ( Illuminate \ Contracts \ Console \ Kernel :: class );
$ status  =  $ kernel -> handle (
    $ input  =  novo  Symfony \ Componente \ Console \ Entrada \ ArgvInput ,
    novo  Symfony \ Componente \ Console \ Saída \ ConsoleOutput
);
/ *
| ------------------------------------------------- -------------------------
| Encerrar o aplicativo
| ------------------------------------------------- -------------------------
|
| Quando o Artisan terminar de executar, dispararemos os eventos de desligamento
| para que qualquer trabalho final possa ser feito pelo aplicativo antes de fecharmos
| abaixo o processo. Esta é a última coisa a acontecer com a solicitação.
|
* /
$ kernel -> terminar ( $ input , $ status );
exit ( $ status );
